version: '3.8'

services:
  db:
    container_name: ${PROJECT_NAME}-db
    hostname: ${MYSQL_CONTAINER_HOSTNAME}
    build:
      context: ./db
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
    platform: linux/amd64
    image: ${PROJECT_NAME}-db
    restart: always
    env_file:
      - ./db/.env.mysql.development
#    environment:
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      TZ: 'Asia/Tokyo'
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ${DATA_HOST_PATH}/mysql-data:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d

  phpmyadmin:
    container_name: ${PROJECT_NAME}-pma
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_ARBITRARY: '1'
      PMA_HOSTS: ${MYSQL_CONTAINER_HOSTNAME}
    ports:
      - ${PMA_PORT}:80
    volumes:
      - ${DATA_HOST_PATH}/phpmyadmin/sessions:/var/lib/mysql
